# Generated by Django 4.2 on 2023-04-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('description', models.TextField(max_length=10000000000)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=100000000)),
                ('other', models.TextField(max_length=100000000)),
                ('time', models.CharField(choices=[('Full time', 'Full Time'), ('Part time', 'Part time'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=30)),
                ('creation_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.company')),
            ],
        ),
    ]
