# Generated by Django 4.2 on 2023-04-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0005_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('good', models.TextField(max_length=200000)),
                ('bad', models.TextField(default='', max_length=2000000)),
                ('additional', models.TextField(default='-', max_length=2000000)),
                ('score', models.IntegerField(default=0)),
                ('creation_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='jrs.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.student')),
            ],
        ),
    ]
