# Generated by Django 4.2 on 2023-04-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200000000)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
