# Generated by Django 4.2 on 2023-04-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=1000000000000000),
        ),
        migrations.AlterField(
            model_name='job',
            name='other',
            field=models.TextField(max_length=100000000000000),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(max_length=1000000000000000),
        ),
    ]
