# Generated by Django 4.2 on 2023-04-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0008_alter_job_description_alter_job_other_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
