# Generated by Django 4.2 on 2023-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0011_searchterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchterm',
            name='search',
        ),
        migrations.AddField(
            model_name='searchterm',
            name='location',
            field=models.CharField(default=0, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchterm',
            name='name',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
    ]
