# Generated by Django 4.2 on 2023-07-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0012_remove_searchterm_search_searchterm_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=500)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(max_length=500)),
                ('q5', models.CharField(max_length=500)),
                ('q6', models.CharField(max_length=500)),
                ('q7', models.CharField(max_length=500)),
                ('q8', models.CharField(max_length=500)),
                ('q9', models.CharField(max_length=500)),
                ('q10', models.CharField(max_length=500)),
                ('q11', models.CharField(max_length=500)),
                ('q12', models.CharField(max_length=500)),
                ('q13', models.CharField(max_length=500)),
                ('q14', models.CharField(max_length=500)),
                ('q15', models.CharField(max_length=500)),
                ('q16', models.CharField(max_length=500)),
                ('q17', models.CharField(max_length=500)),
                ('q18', models.CharField(max_length=500)),
                ('q19', models.CharField(max_length=500)),
                ('q20', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.student')),
            ],
        ),
    ]
